site_name: Moje projekty
site_author: Micha Orman
site_url: https://MichalO88.github.io/my_projects
site_description: >-
    Moje wspaniałe projekty.

repo_name: MichalO88/my_projects
repo_url: https://github.com/MichalO88/my_projects

theme:
  name: material
  palette:
    primary: green
  features:
    - 'toc'  # Ta opcja włącza spis treści
    - 'toc.snappy

nav:
- Strona Domowa: index.md
- Obecny projekt:
  - "Iris": iris/index.md 
- Poprzednie projekty:
  - "Przewidywanie ubezpieczenia": app_predict_insurance/index.md
  
